version: '3.1'
services:

  msc-subscription:
    build: ../
    container_name: msc-subscription
    environment:
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
    ports:
      - "8080:8080"
      - "8787:8787"
    restart: always
    links:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.18
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://10.20.42.23:9200"
      - "ES_TAGS_AS_FIELDS_ALL=true"
    ports:
      - "16686:16686"
    restart: on-failure
    links:
      - elasticsearch